#!/bin/bash

# quick git status
if [ $1 == "s" ]; then
  git status

# quick git commit
elif [ $1 == "commit" ] || [ $1 == "co" ]; then
  git add . && git commit -m "update"

elif [ $1 == "push" ]; then
  git push -u origin `git rev-parse --abbrev-ref HEAD`

# git add commit push
elif [ $1 == "acp" ]; then
  bo co && git push

elif [ $1 == "log" ]; then
  git log --oneline --decorate=no

# delete unused local branches
elif [ $1 == "delete-branch" ]; then
  git branch | egrep -v "(master|\*)" | xargs git branch -D

# kill a running process at port
elif [ $1 == "kill-port" ]; then
  kill $(lsof -ti:$2)



else
  echo "unkonwn command"
fi